version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: soundwave-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: soundwave
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - soundwave-network

  # Backend API
  soundwave-backend:
    build:
      context: ./soundwave-backend
      dockerfile: Dockerfile
    container_name: soundwave-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/soundwave
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./soundwave-backend/uploads:/app/uploads
      - ./soundwave-backend/logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - soundwave-network

  # Frontend React App
  soundwave-frontend:
    build:
      context: ./soundwave-frontend
      dockerfile: Dockerfile
    container_name: soundwave-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - soundwave-backend
    networks:
      - soundwave-network

volumes:
  mongodb_data:
    driver: local

networks:
  soundwave-network:
    driver: bridge